version: '3'

services:
  db:
    # restart: always
    container_name: postgres
    image: postgres:13.5
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
   pgdata: